server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.abc.com
          predicates:
            - Query=url, baidu
        - id: bilibili_route
          uri: https://www.bilibili.com/
          predicates:
            - Query=url, bilibili