server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tArcfighL4d8QTxWzXfbuhtj
      secret-key: KfUUkCsllO6qu1GMFCFoVmh3kktmqMjtuhb
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      sms:
        host: https://smsmsgs.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 1
        appcode:

  application:
    name: gulimall-third-party

